services:
  db-customer:
    container_name: db-customer
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_customers
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431

  db-account:
    container_name: db-account
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_accounts
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
